# Generated by Django 4.0.1 on 2022-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=275)),
                ('type', models.BooleanField(verbose_name=((1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna'), (4, 'Domyślnie fundacja')))),
                ('categories', models.ManyToManyField(to='charityapp.Category')),
            ],
        ),
    ]
